-- Finalechat initial schema.
-- Every identifier is a UUID (v7 where generated by the application so that
-- primary keys sort chronologically). Timestamps are always UTC.

CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE users (
    id            uuid PRIMARY KEY,
    email         citext NOT NULL UNIQUE,
    password_hash text NOT NULL,
    display_name  text NOT NULL DEFAULT '',
    settings      jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE sessions (
    token_hash   bytea PRIMARY KEY,
    user_id      uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    user_agent   text NOT NULL DEFAULT '',
    created_at   timestamptz NOT NULL DEFAULT now(),
    last_seen_at timestamptz NOT NULL DEFAULT now(),
    expires_at   timestamptz NOT NULL
);
CREATE INDEX sessions_user_id_idx ON sessions (user_id);
CREATE INDEX sessions_expires_at_idx ON sessions (expires_at);

CREATE TABLE api_tokens (
    id           uuid PRIMARY KEY,
    user_id      uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name         text NOT NULL,
    token_hash   bytea NOT NULL UNIQUE,
    prefix       text NOT NULL,
    created_at   timestamptz NOT NULL DEFAULT now(),
    last_used_at timestamptz,
    revoked_at   timestamptz
);
CREATE INDEX api_tokens_user_id_idx ON api_tokens (user_id);

CREATE TABLE threads (
    id                uuid PRIMARY KEY,
    user_id           uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    external_id       text,
    title             text NOT NULL DEFAULT '',
    agent             text NOT NULL DEFAULT '',
    meta              jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now(),
    last_activity_at  timestamptz NOT NULL DEFAULT now(),
    last_read_at      timestamptz NOT NULL DEFAULT now(),
    archived_at       timestamptz,
    muted             boolean NOT NULL DEFAULT false,
    preview           text NOT NULL DEFAULT '',
    preview_sender    text NOT NULL DEFAULT ''
);
CREATE UNIQUE INDEX threads_user_external_id_idx ON threads (user_id, external_id) WHERE external_id IS NOT NULL;
CREATE INDEX threads_user_activity_idx ON threads (user_id, last_activity_at DESC);

CREATE TABLE messages (
    id          uuid PRIMARY KEY,
    thread_id   uuid NOT NULL REFERENCES threads(id) ON DELETE CASCADE,
    user_id     uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    sender      text NOT NULL CHECK (sender IN ('agent', 'user', 'system')),
    body        text NOT NULL,
    format      text NOT NULL DEFAULT 'markdown' CHECK (format IN ('markdown', 'text')),
    importance  text NOT NULL DEFAULT 'normal' CHECK (importance IN ('normal', 'important')),
    meta        jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX messages_thread_created_idx ON messages (thread_id, created_at, id);

CREATE TABLE questions (
    id             uuid PRIMARY KEY,
    thread_id      uuid NOT NULL REFERENCES threads(id) ON DELETE CASCADE,
    user_id        uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    prompt         text NOT NULL,
    options        jsonb NOT NULL DEFAULT '[]'::jsonb,
    allow_freeform boolean NOT NULL DEFAULT true,
    multi_select   boolean NOT NULL DEFAULT false,
    status         text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'answered', 'cancelled', 'expired')),
    answer         jsonb,
    meta           jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at     timestamptz NOT NULL DEFAULT now(),
    answered_at    timestamptz,
    expires_at     timestamptz
);
CREATE INDEX questions_thread_created_idx ON questions (thread_id, created_at, id);
CREATE INDEX questions_user_pending_idx ON questions (user_id, created_at DESC) WHERE status = 'pending';

CREATE TABLE push_subscriptions (
    id              uuid PRIMARY KEY,
    user_id         uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    endpoint        text NOT NULL UNIQUE,
    p256dh          text NOT NULL,
    auth            text NOT NULL,
    user_agent      text NOT NULL DEFAULT '',
    created_at      timestamptz NOT NULL DEFAULT now(),
    last_success_at timestamptz,
    failure_count   integer NOT NULL DEFAULT 0
);
CREATE INDEX push_subscriptions_user_id_idx ON push_subscriptions (user_id);
